echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm300 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm300/bjob_DA-runAB__MC-runAB-OOTm300.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm300 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm300/bjob_DA-runAB__MC-runAB-OOTm300.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm50 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm50/bjob_DA-runAB__MC-runAB-OOTm50.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm50 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-OOTm50/bjob_DA-runAB__MC-runAB-OOTm50.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-noPU -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-noPU/bjob_DA-runAB__MC-runAB-noPU.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-noPU -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runAB__MC-runAB-noPU/bjob_DA-runAB__MC-runAB-noPU.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm300 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm300/bjob_DA-runC__MC-runC-OOTm300.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm300 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm300/bjob_DA-runC__MC-runC-OOTm300.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm50 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm50/bjob_DA-runC__MC-runC-OOTm50.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm50 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-OOTm50/bjob_DA-runC__MC-runC-OOTm50.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-noPU -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-noPU/bjob_DA-runC__MC-runC-noPU.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-noPU -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runC__MC-runC-noPU/bjob_DA-runC__MC-runC-noPU.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm300 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm300/bjob_DA-runD__MC-runD-OOTm300.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm300 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm300/bjob_DA-runD__MC-runD-OOTm300.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm50 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm50/bjob_DA-runD__MC-runD-OOTm50.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm50 -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-OOTm50/bjob_DA-runD__MC-runD-OOTm50.sh
echo "bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-noPU -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-noPU/bjob_DA-runD__MC-runD-noPU.sh"
bsub -cwd /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-noPU -q 8nh /afs/cern.ch/work/a/abenagli/NOISE/CompareVariables//output/DA-runD__MC-runD-noPU/bjob_DA-runD__MC-runD-noPU.sh
